# Generated by Django 4.1.3 on 2022-12-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('pay_method', models.CharField(max_length=15)),
                ('amount', models.FloatField(max_length=10)),
                ('description', models.CharField(max_length=50)),
                ('order_date', models.DateField()),
            ],
        ),
    ]
